/**
 * TEXT-TO-SPEECH SERVICE
 * 
 * Purpose: Generate speech from translated text using Kokoro TTS
 * Uses Replicate API with alphanumericuser/kokoro-82m model
 */

const Replicate = require('replicate');
const fs = require('fs').promises;
const path = require('path');
const https = require('https');
const http = require('http');

const REPLICATE_API_TOKEN = process.env.REPLICATE_API_TOKEN;
const KOKORO_MODEL = 'alphanumericuser/kokoro-82m:89b6fa84e4fa2dd6bd3a96be3e1f12827a3516c9fda8fddbac7a0be131c9a6f5';
const DEFAULT_VOICE = process.env.KOKORO_DEFAULT_VOICE || 'af_heart';

// Initialize Replicate client
const replicate = new Replicate({
  auth: REPLICATE_API_TOKEN
});

// Voice mapping per language (using best graded voices)
const VOICE_MAP = {
  'en': 'af_heart',     // Grade A (best overall)
  'es': 'af_heart',     // Use same high-quality voice
  'fr': 'af_heart',     // Use same high-quality voice
  'it': 'af_heart',     // Use same high-quality voice
  'pt': 'af_heart',     // Use same high-quality voice
  'ja': 'af_heart',     // Use same high-quality voice
  'zh': 'af_heart',     // Use same high-quality voice
  'hi': 'af_heart'      // Use same high-quality voice
};

// Language code mapping (full code to single letter)
const LANGUAGE_CODE_MAP = {
  'en': 'a',  // American English
  'es': 'e',  // Spanish
  'fr': 'f',  // French
  'it': 'i',  // Italian
  'pt': 'p',  // Brazilian Portuguese
  'ja': 'j',  // Japanese
  'zh': 'z',  // Mandarin Chinese
  'hi': 'h'   // Hindi
};

/**
 * Download audio file from URL
 * @param {string} url - Audio file URL
 * @param {string} outputPath - Path to save audio file
 * @returns {Promise<string>} - Path to downloaded file
 */
async function downloadAudio(url, outputPath) {
  return new Promise((resolve, reject) => {
    const protocol = url.startsWith('https') ? https : http;
    const file = require('fs').createWriteStream(outputPath);
    
    protocol.get(url, (response) => {
      response.pipe(file);
      file.on('finish', () => {
        file.close();
        resolve(outputPath);
      });
    }).on('error', (err) => {
      require('fs').unlink(outputPath, () => {}); // Delete partial file
      reject(err);
    });
  });
}

/**
 * Generate speech from text using Kokoro TTS
 * @param {string} text - Text to convert to speech
 * @param {string} language - Language code (e.g., 'en', 'es')
 * @param {string} outputPath - Path to save generated audio (optional)
 * @returns {Promise<string>} - Path to generated audio file
 */
async function generateSpeech(text, language = 'en', outputPath = null) {
  try {
    // Select voice based on language (using af_heart for all as per client decision)
    const voice = VOICE_MAP[language] || DEFAULT_VOICE;
    const languageCode = LANGUAGE_CODE_MAP[language] || 'a'; // Default to American English
    
    console.log(`🎙️  Generating speech for language: ${language}`);
    console.log(`   Voice: ${voice}`);
    console.log(`   Language Code: ${languageCode}`);
    console.log(`   Text: "${text.substring(0, 50)}..."`);
    
    // Call Replicate API
    const output = await replicate.run(
      KOKORO_MODEL,
      {
        input: {
          text: text,
          voice: voice,
          language_code: languageCode,
          speed: 1.0
        }
      }
    );
    
    console.log(`   ✓ Speech generated by Replicate`);
    
    // Generate output path if not provided
    if (!outputPath) {
      const timestamp = Date.now();
      const filename = `tts_${language}_${timestamp}.wav`;
      outputPath = path.join(process.cwd(), 'temp', filename);
    }
    
    // Ensure directory exists
    await fs.mkdir(path.dirname(outputPath), { recursive: true });
    
    // Write the file directly (output is a file buffer)
    console.log(`   � Saving audio...`);
    await fs.writeFile(outputPath, output);
    
    const stats = await fs.stat(outputPath);
    console.log(`   ✓ Audio saved: ${path.basename(outputPath)} (${(stats.size / 1024).toFixed(2)} KB)\n`);
    
    return outputPath;
    
  } catch (error) {
    console.error(`TTS generation failed (${language}):`, error.message);
    throw new Error(`Failed to generate speech: ${error.message}`);
  }
}

/**
 * Generate speech for multiple languages
 * @param {object} translations - Object with language codes as keys and text as values
 * @returns {Promise<object>} - Object with language codes as keys and audio paths as values
 */
async function batchGenerateSpeech(translations) {
  try {
    console.log(`\n🎙️  Batch generating speech for ${Object.keys(translations).length} languages...\n`);
    
    const audioFiles = {};
    
    // Generate speech for each language sequentially
    for (const [lang, text] of Object.entries(translations)) {
      audioFiles[lang] = await generateSpeech(text, lang);
    }
    
    console.log(`✓ All speech files generated\n`);
    return audioFiles;
    
  } catch (error) {
    console.error('Batch TTS generation failed:', error.message);
    throw error;
  }
}

module.exports = {
  generateSpeech,
  batchGenerateSpeech
};
